# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Algoritmos.ui'
#
# Created: Sun Nov 02 21:55:24 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(864, 459)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 811, 241))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab0 = QtGui.QWidget()
        self.tab0.setObjectName(_fromUtf8("tab0"))
        self.t0_a1 = QtGui.QCheckBox(self.tab0)
        self.t0_a1.setGeometry(QtCore.QRect(20, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t0_a1.setFont(font)
        self.t0_a1.setObjectName(_fromUtf8("t0_a1"))
        self.t0_a2 = QtGui.QCheckBox(self.tab0)
        self.t0_a2.setGeometry(QtCore.QRect(20, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t0_a2.setFont(font)
        self.t0_a2.setObjectName(_fromUtf8("t0_a2"))
        self.t0_a3 = QtGui.QCheckBox(self.tab0)
        self.t0_a3.setGeometry(QtCore.QRect(20, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t0_a3.setFont(font)
        self.t0_a3.setObjectName(_fromUtf8("t0_a3"))
        self.t0_a4 = QtGui.QCheckBox(self.tab0)
        self.t0_a4.setGeometry(QtCore.QRect(400, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t0_a4.setFont(font)
        self.t0_a4.setObjectName(_fromUtf8("t0_a4"))
        self.t0_a5 = QtGui.QCheckBox(self.tab0)
        self.t0_a5.setGeometry(QtCore.QRect(400, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t0_a5.setFont(font)
        self.t0_a5.setObjectName(_fromUtf8("t0_a5"))
        self.tabWidget.addTab(self.tab0, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.t1_a3 = QtGui.QCheckBox(self.tab1)
        self.t1_a3.setGeometry(QtCore.QRect(410, 20, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t1_a3.setFont(font)
        self.t1_a3.setObjectName(_fromUtf8("t1_a3"))
        self.t1_a2 = QtGui.QCheckBox(self.tab1)
        self.t1_a2.setGeometry(QtCore.QRect(30, 110, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t1_a2.setFont(font)
        self.t1_a2.setObjectName(_fromUtf8("t1_a2"))
        self.t1_a1 = QtGui.QCheckBox(self.tab1)
        self.t1_a1.setGeometry(QtCore.QRect(30, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t1_a1.setFont(font)
        self.t1_a1.setObjectName(_fromUtf8("t1_a1"))
        self.t1_a4 = QtGui.QCheckBox(self.tab1)
        self.t1_a4.setGeometry(QtCore.QRect(410, 110, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t1_a4.setFont(font)
        self.t1_a4.setObjectName(_fromUtf8("t1_a4"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.t2_a4 = QtGui.QCheckBox(self.tab2)
        self.t2_a4.setGeometry(QtCore.QRect(410, 20, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t2_a4.setFont(font)
        self.t2_a4.setObjectName(_fromUtf8("t2_a4"))
        self.t2_a2 = QtGui.QCheckBox(self.tab2)
        self.t2_a2.setGeometry(QtCore.QRect(30, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t2_a2.setFont(font)
        self.t2_a2.setObjectName(_fromUtf8("t2_a2"))
        self.t2_a1 = QtGui.QCheckBox(self.tab2)
        self.t2_a1.setGeometry(QtCore.QRect(30, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t2_a1.setFont(font)
        self.t2_a1.setObjectName(_fromUtf8("t2_a1"))
        self.t2_a3 = QtGui.QCheckBox(self.tab2)
        self.t2_a3.setGeometry(QtCore.QRect(30, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t2_a3.setFont(font)
        self.t2_a3.setObjectName(_fromUtf8("t2_a3"))
        self.t2_a5 = QtGui.QCheckBox(self.tab2)
        self.t2_a5.setGeometry(QtCore.QRect(410, 80, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t2_a5.setFont(font)
        self.t2_a5.setObjectName(_fromUtf8("t2_a5"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.t3_a2 = QtGui.QCheckBox(self.tab3)
        self.t3_a2.setGeometry(QtCore.QRect(30, 80, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t3_a2.setFont(font)
        self.t3_a2.setObjectName(_fromUtf8("t3_a2"))
        self.t3_a1 = QtGui.QCheckBox(self.tab3)
        self.t3_a1.setGeometry(QtCore.QRect(30, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t3_a1.setFont(font)
        self.t3_a1.setObjectName(_fromUtf8("t3_a1"))
        self.t3_a3 = QtGui.QCheckBox(self.tab3)
        self.t3_a3.setGeometry(QtCore.QRect(30, 150, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t3_a3.setFont(font)
        self.t3_a3.setObjectName(_fromUtf8("t3_a3"))
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.t4_a3 = QtGui.QCheckBox(self.tab4)
        self.t4_a3.setGeometry(QtCore.QRect(30, 150, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t4_a3.setFont(font)
        self.t4_a3.setObjectName(_fromUtf8("t4_a3"))
        self.t4_a2 = QtGui.QCheckBox(self.tab4)
        self.t4_a2.setGeometry(QtCore.QRect(30, 80, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t4_a2.setFont(font)
        self.t4_a2.setObjectName(_fromUtf8("t4_a2"))
        self.t4_a1 = QtGui.QCheckBox(self.tab4)
        self.t4_a1.setGeometry(QtCore.QRect(30, 20, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t4_a1.setFont(font)
        self.t4_a1.setObjectName(_fromUtf8("t4_a1"))
        self.tabWidget.addTab(self.tab4, _fromUtf8(""))
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName(_fromUtf8("tab5"))
        self.t5_a3 = QtGui.QCheckBox(self.tab5)
        self.t5_a3.setGeometry(QtCore.QRect(20, 150, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t5_a3.setFont(font)
        self.t5_a3.setObjectName(_fromUtf8("t5_a3"))
        self.t5_a2 = QtGui.QCheckBox(self.tab5)
        self.t5_a2.setGeometry(QtCore.QRect(20, 80, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t5_a2.setFont(font)
        self.t5_a2.setObjectName(_fromUtf8("t5_a2"))
        self.t5_a1 = QtGui.QCheckBox(self.tab5)
        self.t5_a1.setGeometry(QtCore.QRect(20, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.t5_a1.setFont(font)
        self.t5_a1.setObjectName(_fromUtf8("t5_a1"))
        self.tabWidget.addTab(self.tab5, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 340, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 340, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Seleccione El Algoritmo Que Desea Probar", None))
        self.t0_a1.setText(_translate("MainWindow", "Metodo de Biseccion", None))
        self.t0_a2.setText(_translate("MainWindow", "Metodo de Newton", None))
        self.t0_a3.setText(_translate("MainWindow", "Metodo de Secante", None))
        self.t0_a4.setText(_translate("MainWindow", "Metodo de la Falsa Posicion", None))
        self.t0_a5.setText(_translate("MainWindow", "Metodo de Muller", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindow", "Ceros", None))
        self.t1_a3.setText(_translate("MainWindow", "Interpolacion Mediante Trazadores \n"
"Cubicos Naturales", None))
        self.t1_a2.setText(_translate("MainWindow", "Interpolacion Polinomial \n"
"de Newton", None))
        self.t1_a1.setText(_translate("MainWindow", "Interpolacion de Lagrange", None))
        self.t1_a4.setText(_translate("MainWindow", "Interpolacion Mediante Trazadores \n"
"Cubicos Sujetos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Interpolacion", None))
        self.t2_a4.setText(_translate("MainWindow", "Integracion Numerica: \n"
"Simpson", None))
        self.t2_a2.setText(_translate("MainWindow", "Diferenciacion Numerica", None))
        self.t2_a1.setText(_translate("MainWindow", "Metodo de Punto Fijo", None))
        self.t2_a3.setText(_translate("MainWindow", "Integracion Numerica: \n"
"Regla del Trapecio", None))
        self.t2_a5.setText(_translate("MainWindow", "Integracion Numerica Cuadraturas \n"
"de Gauss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Diferenciacion/Integracion", None))
        self.t3_a2.setText(_translate("MainWindow", "Solucion de EDO: Runge Kutta", None))
        self.t3_a1.setText(_translate("MainWindow", "Solucion de EDO: Metodo de Euler", None))
        self.t3_a3.setText(_translate("MainWindow", "Sistemas de EDO: Runge Kutta", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Ecuacion Diferencial Ordinaria", None))
        self.t4_a3.setText(_translate("MainWindow", "Sitemas de Ecuaciones Mediante La Inversa", None))
        self.t4_a2.setText(_translate("MainWindow", "Sitemas de Ecuaciones Por Eliminacion de Gauss Jordan", None))
        self.t4_a1.setText(_translate("MainWindow", "Sitemas de Ecuaciones Por Eliminacion de Gauss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "Sistemas de Ecuaciones", None))
        self.t5_a3.setText(_translate("MainWindow", "Metodo Lineal de Diferencias Finitas", None))
        self.t5_a2.setText(_translate("MainWindow", "Regresion Lineal", None))
        self.t5_a1.setText(_translate("MainWindow", "Descomposicion LU", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "Otros", None))
        self.pushButton.setText(_translate("MainWindow", "Historial", None))
        self.pushButton_2.setText(_translate("MainWindow", "Algoritmo", None))

