# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windice.ui'
#
# Created: Thu Jun 19 15:27:10 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WIndice(object):
    def setupUi(self, WIndice):
        WIndice.setObjectName(_fromUtf8("WIndice"))
        WIndice.resize(400, 347)
        self.buttonBox = QtGui.QDialogButtonBox(WIndice)
        self.buttonBox.setGeometry(QtCore.QRect(40, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tableWidget = QtGui.QTableWidget(WIndice)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 381, 271))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(13)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)

        self.retranslateUi(WIndice)

    def retranslateUi(self, WIndice):
        WIndice.setWindowTitle(_translate("WIndice", "Dialog", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("WIndice", "Imer", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("WIndice", "William", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("WIndice", "Juan Carlos", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("WIndice", "Erick", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("WIndice", "Edward", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("WIndice", "Donaldo", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("WIndice", "Gadiel", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("WIndice", "Gadiel", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("WIndice", "Mario", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("WIndice", "William", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("WIndice", "Donaldo", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("WIndice", "Edward", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("WIndice", "Juan Carlos", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("WIndice", "Algoritmo", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("WIndice", "Nombre Archivo", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("WIndice", "Interpolacion de Lagrange", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("WIndice", "lagrange2.py", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("WIndice", "Interpolacion Mediante Trazadores Cubicos Naturales", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("WIndice", "Trazador_cubico_natural.py", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("WIndice", "Diferenciacion Numerica mediante Polinomios de Lagrange", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("WIndice", "derivPLagrange.py", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("WIndice", "Integracion Numerica por la Regla del Trapecio", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("WIndice", "trapezoide.py", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("WIndice", "Integracion Numerica por el Metodo de Simpson", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("WIndice", "simpson.py", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("WIndice", "Integracion Numerica por la Cuadratura Gaussiana", None))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("WIndice", "CuadraturaGaussiana.py", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("WIndice", "Solucion de EDO por Euler", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("WIndice", "euler_ec_dif.py", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("WIndice", "Solucion EDO por Runge-Kutta", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("WIndice", "runge_kutta_ecu_dif", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("WIndice", "Sistemas de Ecuaciones por Eliminacion de Gauss", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("WIndice", "sistema_ecuaciones_gauss.py", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("WIndice", "Factorizacion LU", None))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("WIndice", "Factorizacion_LU.py", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("WIndice", "Sistema de Ecuacioes mediante la Inversa", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("WIndice", "MatrizInversa.py", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("WIndice", "Regresion Lineal", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("WIndice", "minimos_cuadrados.py", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("WIndice", "Metodo Lineal de Diferencias Finitas", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("WIndice", "lineal_diferencias_finitas.py", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

